### ISSUE TITLE
black screen while starting a new game

### ISSUE THREAD

**Issue by harryzhen** [justedm/FTK-MultiMax-Rework#1]
<img width="722" alt="image" src="https://github.com/justedm/FTK-MultiMax-Rework/assets/117997867/774a4a45-238f-45c2-a64d-c858929e2e01">
black screen while starting a new game

**Comment by justedm** [comment]
Thanks for opening an issue, its an already known problem that im working on a fix.
Just to have more info, are you trying to start a Local or Online coop game? 
Also is the number of players in the config file the same number of the players that joined the game?

**Comment by justedm** [comment]
> <img alt="image" width="722" src="https://private-user-images.githubusercontent.com/117997867/297130806-774a4a45-238f-45c2-a64d-c858929e2e01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MzMxMzIsIm5iZiI6MTcwNTQzMjgzMiwicGF0aCI6Ii8xMTc5OTc4NjcvMjk3MTMwODA2LTc3NGE0YTQ1LTIzOGYtNDVjMi1hNjRkLWM4NTg5MjllMmUwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQxOTIwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDU5NzczNGIzYzZlY2JhNmI3NGZiNDNhOGIzYWE5YTY1OTdiMDYxMjIyODU1N2Y2OWY3OTg1YWFhNTFjYWEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.47Qhvhi6G4-Ef6cyC2mkNuLtrxjaVQ91juhv6CkfnaQ"> black screen while starting a new game

Thanks for opening an issue, its an already known problem that im working on a fix.
Just to have more info, are you trying to start a Local or Online coop game?
Also is the number of players in the config file the same number of the players that joined the game?

**Comment by harryzhen** [comment]
I have tried both Local and Online coop game with my friends , and this problem always happened.
The number of players in the config file is set in the same number of the player that joined the game,but it is always a black screen when a game started.
Only when we set the number into 3 the game work out normally.

**Comment by justedm** [comment]
> I have tried both Local and Online coop game with my friends , and this problem always happened. The number of players in the config file is set in the same number of the player that joined the game,but it is always a black screen when a game started. Only when we set the number into 3 the game work out normally.

Black screen error should now be solved, let me know if you still encounter any problems.
Will wait for your confirmation before closing issue

**Comment by harryzhen** [comment]
It worked ! Thank you for your work!
