### ISSUE TITLE
The game may stuck while entering a fight

### ISSUE THREAD

**Issue by harryzhen** [justedm/FTK-MultiMax-Rework#2]
<img width="490" alt="image" src="https://github.com/justedm/FTK-MultiMax-Rework/assets/117997867/f80b1bd6-f8f7-4d58-9bba-9be62d234099">
Oh no ! Another bug !
The game may stuck while entering a fight.

**Comment by justedm** [comment]
> <img alt="image" width="490" src="https://private-user-images.githubusercontent.com/117997867/297266815-f80b1bd6-f8f7-4d58-9bba-9be62d234099.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0ODY5MzcsIm5iZiI6MTcwNTQ4NjYzNywicGF0aCI6Ii8xMTc5OTc4NjcvMjk3MjY2ODE1LWY4MGIxYmQ2LWY4ZjctNGQ1OC05YmJhLTliZTYyZDIzNDA5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QxMDE3MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDAzODlmYWU1N2Q0NTM0MzBlNDdlNWE2Y2FiMmI0ZDQxNTI4NGYzMWViZTdmNGExNGU3ZGQzNWE0Y2JlYzFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JBta3X2QUxgRmM4ShPwxIaMgYqWmsjM5OKo3muHMlwU"> Oh no ! Another bug ! The game may stuck while entering a fight.

Ouch, last patch may have broke something...
It should be fixed now! 😃 

let me know if you encounter any other errors!

**Comment by harryzhen** [comment]
It seems to be all right for now. I will try it later with my friends
