### ISSUE TITLE
The game sometimes stuck while starting the game.

### ISSUE THREAD

**Issue by harryzhen** [justedm/FTK-MultiMax-Rework#3]
<img width="489" alt="image" src="https://github.com/justedm/FTK-MultiMax-Rework/assets/117997867/37094d8e-d84b-4194-8bcf-72f106f74e67">
The game sometimes stuck while starting the game.

**Comment by justedm** [comment]
> <img alt="image" width="489" src="https://private-user-images.githubusercontent.com/117997867/298284056-37094d8e-d84b-4194-8bcf-72f106f74e67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3Nzc3MzksIm5iZiI6MTcwNTc3NzQzOSwicGF0aCI6Ii8xMTc5OTc4NjcvMjk4Mjg0MDU2LTM3MDk0ZDhlLWQ4NGItNDE5NC04YmNmLTcyZjEwNmY3NGU2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQxOTAzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDc5NmQxMGU2ZGU2ZjkwNTNlOWRkODhmYmY0MWE2OTI4MTQ0Nzk5MDI0OTdhNWQwZmQzODNlZGFmYzJlNjk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zl--iX_aEMz54MGzWmpanMeYQRHCyHS5broa7EJm5yU"> The game sometimes stuck while starting the game.

Already known bug that will need to be fixed, kinda hard to reproduce so i will work on it once im able to do so.
For now restarting seems to get it to work
