### ISSUE TITLE
The game may stuck after a fight on the ship

### ISSUE THREAD

**Issue by harryzhen** [justedm/FTK-MultiMax-Rework#4]
<img width="484" alt="image" src="https://github.com/justedm/FTK-MultiMax-Rework/assets/117997867/b3cc33f7-726a-4c4f-b606-4f0f62c5481b">
The game may stuck after a fight on the ship

**Comment by justedm** [comment]
> <img alt="image" width="484" src="https://private-user-images.githubusercontent.com/117997867/298287835-b3cc33f7-726a-4c4f-b606-4f0f62c5481b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3Nzc4MjAsIm5iZiI6MTcwNTc3NzUyMCwicGF0aCI6Ii8xMTc5OTc4NjcvMjk4Mjg3ODM1LWIzY2MzM2Y3LTcyNmEtNGM0Zi1iNjA2LTRmMGY2MmM1NDgxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQxOTA1MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOGZhOWE3OTU2NTYyMGU3NTYwM2MzZjVmZTgyMjUwNGFmYTIxMzg3YzlmOWFkNjMyMmI5MWY2Y2E4MWFhMjg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Mt9BVcRR7ijRcyZD6AqpzwuIfQCyZKCLCyNNTDAoRP4"> The game may stuck after a fight on the ship

Can you please provide me the game file where you are getting this error? I tried to reproduce it in game but i was able to navigate with a boat without any problems.
The save file is inside of this folder:

AppData\LocalLow\IronOak Games\FTK\save and its a .run file (example: KillVexor_2024_1_20_0.run)

**Comment by harryzhen** [comment]
I'm sorry that I can't provide the game file
We have already finished that game by avoiding fights on the ship...

**Comment by harryzhen** [comment]
We play in 4 players ,  Adventure "For The King".
The error act as we stuck at the place where we fight , all move point we rest lost, and the player who in control can't skip his turn.

**Comment by justedm** [comment]
> We play in 4 players , Adventure "For The King". The error act as we stuck at the place where we fight , all move point we rest lost, and the player who in control can't skip his turn.

This error should be now fixed aswell!
Thanks for your help by opening the issue as well. ❤️
