### ISSUE TITLE
Doesn't load properly when creating a new game.

### ISSUE THREAD

**Issue by LovesickLunatik** [justedm/FTK-MultiMax-Rework#5]
![image_2024-01-29_134137683](https://github.com/justedm/FTK-MultiMax-Rework/assets/158089466/c2453be1-eb8c-4075-82f2-50f7c6d36810)
This is what is shown in the console, I was attempting to start a 4 player game after editing the config file and saving it.

**Comment by justedm** [comment]
> ![image_2024-01-29_134137683](https://private-user-images.githubusercontent.com/158089466/300569138-c2453be1-eb8c-4075-82f2-50f7c6d36810.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTEwOTMsIm5iZiI6MTcwNjY5MDc5MywicGF0aCI6Ii8xNTgwODk0NjYvMzAwNTY5MTM4LWMyNDUzYmUxLWViOGMtNDA3NS04MmYyLTUwZjdjNmQzNjgxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQwODQ2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjFjYjgxNGI4MTczODk5YzFjMDFiMDZmZmQ1NTU0MmQ5NzhmMDdjYWVjMjkwOTc2ZTdlNzlhNzIyMDVhMzY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.A0IhJxHIPlzhTEbIoHa_afiimApZ9D9_BTNn2D2RJcY) This is what is shown in the console, I was attempting to start a 4 player game after editing the config file and saving it.

Tried to replicate the problem but couldn't get the error, i managed to create and start the game correctly.
If it was online coop, did everyone that joined had the mod installed? (They need to have 4 max players in the config too)

**Comment by justedm** [comment]
Closed 'cause of inactivity, also can't reproduce
