### ISSUE TITLE
Two bugs

### ISSUE THREAD

**Issue by Senjay-id** [justedm/FTK-MultiMax-Rework#6]
Forwarding the bug report from nexus https://www.nexusmods.com/fortheking/mods/7?tab=bugs

Using bepinex 5.4.22 with no other mod, and playing with 5 player and also happen with 4 player.

1st bug
When fighting an enemy with full party and when it's the enemy turn, they do nothing, thus softlocking the game.

2nd bug
Sometimes when starting the game after picking the class the game goes blackscreen indefinitely, forcing to restart the game.

Note
When playing with maxplayers set to 3, the first bug didn't happen

**Comment by justedm** [comment]
I've replied to you on nexus mods, please reply there
